# Appveyor is used for Windows testing.
# Travis-CI for Linux testing, OSX testing, generating coverage,
# uploading coverage to Codacy, building documentation,
# deploying documentation.

image:
- Visual Studio 2017

build: false

environment:

  matrix:
    - PYTHON: "C:\\Python3.6"
      TOX_ENV: "py36"

    - PYTHON: "C:\\Python3.6-x64"
      TOX_ENV: "py36"

    - PYTHON: "C:\\Python3.7"
      TOX_ENV: "py37"

    - PYTHON: "C:\\Python3.7-x64"
      TOX_ENV: "py37"

    - PYTHON: "C:\\Python3.8"
      TOX_ENV: "py38"

    - PYTHON: "C:\\Python3.8-x64"
      TOX_ENV: "py38"

matrix:
  allow_failures:
    - TOX_ENV: "py38"

install:

  # Perpend python to PATH
  - cmd: set PATH=%PYTHON%\Scripts;%PYTHON%;%PATH%
  # Check that we have the expected version of Python
  - cmd: python --version

  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - cmd: python -m pip install --upgrade pip

  # Install tox an poetry
  - cmd: pip install tox

test_script:
  - cmd: tox -e %TOX_ENV%"

notifications:
  - provider: Email
    to:
    - mikevansighem@gmail.com
    subject: Thea build failed
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
