site_name: 'Thea'
site_description: 'Documentation for Thea.'
site_author: 'Mike van Sighem'
site_url: 'https://mikevansighem.github.io/thea/'
copyright: 'Copyright 2018 - Mike van Sighem'
repo_name: 'mikevansighem/thea'
repo_url: 'https://github.com/mikevansighem/thea'

nav:
  - Welcome: index.md
  - Getting started: welcome/getting_started.md
  - How it works: welcome/how_it_works.md
  - Haveing issues?!: welcome/haveing_issues.md
  - Planned features: PLANNED.md
  - Changelog: CHANGELOG.md
  - License: LICENSE.md

  - Environment:
    - Solar position: not_available.md

  - Hardware:
    - MQTT-module: not_available.md

  - Developer guide:
    - Contributing: CONTRIBUTING.md
    - Working on code: dev_guide/contributing_code.md
    - Testing and CI: dev_guide/testing_and_ci.md
    - Releasing: dev_guide/releasing.md

  - API refrence:
    - Item stores: api_refrence/item_stores.md

theme:
  name: 'material'
  favicon: 'images/favicon.ico'
  logo: 'images/thea_icon.svg'
  language: 'en'

  palette:
    primary: 'purple'
    accent: 'purple'

  feature:
    tabs: true

markdown_extensions:
  - codehilite
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
